export enum EnvConfig {
	NODE_ENV = 'NODE_ENV',
	PORT = 'PORT',

	// JWT
	JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET',
	JWT_ACCESS_TOKEN_EXPIRATION_TIME = 'JWT_ACCESS_TOKEN_EXPIRATION_TIME',
	JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET',
	JWT_REFRESH_TOKEN_EXPIRATION_TIME = 'JWT_REFRESH_TOKEN_EXPIRATION_TIME',

	// ORM
	ORM_TYPE = 'ORM_TYPE',
	ORM_DATABASE = 'ORM_DATABASE',
	ORM_ENTITIES = 'ORM_ENTITIES',
	ORM_AUTO_LOAD_ENTITIES = 'ORM_AUTO_LOAD_ENTITIES',
	ORM_DROP_SCHEMA = 'ORM_DROP_SCHEMA',
	ORM_SYNCHRONIZE = 'ORM_SYNCHRONIZE',
	ORM_LOGGING = 'ORM_LOGGING',
}
